manifest = "42cf781436cf473904abe1afb195ba26de4437ede903c4f6528884a63e1de2c7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
target = "//:functional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
target = "//:lexical-cast"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "branch=master" ]
revision = "6587b84e4fb0711bd7d0930b415ca7937e72021b"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "branch=master" ]
revision = "f326ae1e1b93216ce40e098a2baed4cc152d06ef"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "417f80abf86251b29609a9747dae7756236699aa"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "branch=master" ]
revision = "783ec0afe46d65f8cfdb558e16f25adc02797b3c"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "branch=master" ]
revision = "4dcd765d7933cb9419d9120cbf8df7d83e38f9db"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "60c77dd14f5bac2b9e6c59f308b7ad20d31f70ab"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "bb4226c58e17f8880779f19559a50e497f2bfcba"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "ddd9a887f1f0253ded4455d455b3c54228067b74"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "54bb4a90a75f96cc22e3376f8a3221f96aa80528"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "branch=master" ]
revision = "291485cbda77efaee017c03dbc67c09f8abe303e"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "branch=master" ]
revision = "bb8ffe4d24071f3942a18b274cc7f3ee0dc91eb2"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "branch=master" ]
revision = "a241f4f12c8b0e0f1d5d803eb5404c5d67ea254b"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "d812ed3ac7c7d573249e49fe23aa12339629c730"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "branch=master" ]
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "branch=master" ]
revision = "9f6d656caf4b0037327c426219de6ef676a2ccdc"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "branch=master" ]
revision = "35fa920e0b53c124b0b5972b1802032933c71fca"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "branch=master" ]
revision = "9c3529ad17d35171ffaa689ebfee9f21ce616129"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "branch=master" ]
revision = "10482c9459133c139137e459d8e1051246866983"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "branch=master" ]
revision = "7a147d3e6bead2fba47b60365fe1ae0c308768d5"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "8256c9846a133573ff959e0a7dc0cadb8fba5192"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "e5d869f860393e8744ea34c70456d5d6dde1c308"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "b8e0fcc49cede65c3b4ef18ed5aa797225578467"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"
